name: Build and Deploy Angular App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ğŸ“¦ Clean install (workaround for Rollup bug)
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: âœ… Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        continue-on-error: false  # Fail the workflow if tests fail

      - name: ğŸ› ï¸ Build Angular app
        run: npm run build -- --configuration production --base-href=/cicd/

      # - name: ğŸš€ Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages           # The branch the action should deploy to.
      #     folder: dist/cicd/browser  # The folder the action should deploy.
      #     token: ${{ secrets.cicd }}

      - name: â˜ï¸ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIA5QVJ6BLKWJ5E437U }}
          aws-secret-access-key: ${{ secrets.1GGXhF9HjelgT5Cw65XjO0H6NPLAyYpZAQYKWKlq }}
          aws-region: eu-north-1 # Change this to your region (e.g., us-east-1)

      - name: ğŸ“¤ Deploy to S3
        run: |
          aws s3 sync dist/cicd/browser s3://your-s3-bucket-name --delete
